# Generated by Django 5.2.16 on 2026-07-30 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optionally starting with +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
