# Generated by Django 5.2.16 on 2026-07-30 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must look like MIT-2024-001 (MIT-YYYY-NNN).', regex='^MIT-\\d{4}-\\d{3}$')]),
        ),
    ]
