# Generated by Django 5.2.16 on 2026-07-30 04:09

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[students.models.validate_date_of_birth]),
        ),
    ]
