# Generated by Django 6.0.7 on 2026-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
    ]
