# Generated by Django 6.0.7 on 2026-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_backfill_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_date', 'id']},
        ),
    ]
