# Generated by Django 5.2.16 on 2026-08-05 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECAActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('club', 'Club'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eca_activities_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='eca_activity',
            field=models.ForeignKey(blank=True, help_text="Which activity this record's 'eca' status refers to, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.ecaactivity'),
        ),
    ]
