# Generated by Django 6.0.7 on 2026-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_ecaactivity_attendance_eca_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'id']},
        ),
    ]
