# Generated by Django 6.0.7 on 2026-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('lp', 'Late Present'), ('eca', 'Extra-Curricular Activity')], max_length=10),
        ),
    ]
